name = "Mirrors"
uuid = "879c85a0-8f14-11e8-0652-af3058d99549"
author = ["Sunoru <s@sunoru.com>"]
repo = "https://github.com/sunoru/Mirrors.jl.git"
version = "1.0.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
